"""Generated provider types, so an editor completes ``let.providers.<alias>.<accelerator>``.

Aliases live in ``.letify`` rather than in code, so a type checker cannot know them. This
module writes ``letify_providers.pyi`` into the project, naming each alias the project can use
as a class and each accelerator the account offers as an attribute. ``Launcher.providers`` is
typed as ``letify_providers.ProvidersView``, and letify ships a plain fallback of that module,
so a project that never generated a stub keeps the ordinary types.

Writing the stub never connects to anything. Accelerators come from the entry's own ``devices``
table or ``gpus`` list, from the fixed lists Colab and Modal publish, or from this machine's
cards for ``local``. An account whose accelerators would have to be asked for over the network
keeps attribute lookup typed as ``Instance``.
"""

from __future__ import annotations

import keyword
import os
import re
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING

from .config.inventory import read_table
from .errors import LetifyError

if TYPE_CHECKING:
    from .launcher import Launcher
    from .providers.base import Provider

#: The module a type checker resolves ``Launcher.providers`` through.
FILE_NAME = "letify_providers.pyi"

#: Pyright's and Pylance's default stub path, relative to the project root.
DEFAULT_DIRECTORY = "typings"

#: Set to ``0`` to stop ``Launcher()`` from writing the stub.
ENVIRONMENT = "LETIFY_STUBS"

#: Names the generated module already uses, which an alias's class must not take.
_TAKEN = frozenset({"Instance", "ProvidersView", "letify"})

HEADER = """\
# Generated by letify from the .letify files this project reads. Do not edit: letify rewrites
# it when the accounts or their accelerators change. It reflects this machine's ~/.letify, so
# keep it out of version control.
"""


def class_name(alias: str) -> str:
    """The alias in CamelCase, as ``colab_pro`` to ``ColabPro``.

    A result that is a Python keyword, such as ``None`` from the alias ``none``, gets
    ``Provider`` appended so the stub still parses.
    """
    parts = [part for part in re.split(r"_+", alias) if part]
    name = "".join(part[:1].upper() + part[1:] for part in parts) or "Provider"
    if keyword.iskeyword(name):
        name += "Provider"
    return name


def project_root(start: Path | None = None) -> Path:
    """The nearest directory upward that holds a ``pyproject.toml``, or the start itself."""
    here = (start or Path.cwd()).resolve()
    for folder in (here, *here.parents):
        if (folder / "pyproject.toml").is_file():
            return folder
    return here


def target(root: Path | None = None) -> Path | None:
    """Where the stub goes, or ``None`` when the project turned generation off.

    ``[tool.letify] typings`` in the project's ``pyproject.toml`` names the directory relative
    to the root. ``typings = false`` turns generation off.
    """
    root = root or project_root()
    directory = DEFAULT_DIRECTORY
    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        try:
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError):
            data = {}
        section = data.get("tool", {}).get("letify", {})
        setting = section.get("typings", DEFAULT_DIRECTORY) if isinstance(section, dict) else None
        if setting is False:
            return None
        if isinstance(setting, str) and setting:
            directory = setting
    return root / directory / FILE_NAME


def _accelerators(provider: Provider) -> list[str] | None:
    """Accelerator names that can be known without a network call, or ``None``."""
    from .providers import Colab, Local, Modal

    declared = read_table(provider.config.options)
    if declared:
        names = list(declared)
    elif isinstance(provider, (Colab, Local, Modal)):
        names = list(provider.instances)
    else:
        return None
    return [name for name in names if name.isidentifier() and not keyword.iskeyword(name)]


def render(launcher: Launcher) -> str:
    """The stub text for the accounts this project can use."""
    lines = [
        HEADER,
        "import letify.launcher",
        "import letify.providers",
        "from letify.declare.instance import Instance",
        "",
    ]
    taken = set(_TAKEN)
    view: list[tuple[str, str]] = []

    for alias in launcher.config.order:
        try:
            provider = launcher.provider(alias)
        except LetifyError:
            view.append((alias, "letify.providers.Provider"))
            continue

        name = class_name(alias)
        if name in taken:
            number = 2
            while f"{name}{number}" in taken:
                number += 1
            name = f"{name}{number}"
        taken.add(name)

        lines.append("")
        lines.append(f"class {name}(letify.providers.{type(provider).__name__}):")
        accelerators = _accelerators(provider)
        if accelerators is None:
            lines.append("    def __getattr__(self, name: str) -> Instance: ...")
        else:
            lines.extend(f"    {accelerator}: Instance" for accelerator in accelerators)
            # Declaring no lookup makes a misspelled accelerator a type error.
            lines.append("    __getattr__: None  # type: ignore[assignment]")
        view.append((alias, name))

    lines.append("")
    lines.append("")
    lines.append("class ProvidersView(letify.launcher.Providers):")
    lines.append("    any: letify.launcher.AnyProvider")
    lines.extend(f"    {alias}: {annotation}" for alias, annotation in view)
    lines.append("    __getattr__: None  # type: ignore[assignment]")
    return "\n".join(lines) + "\n"


def write(launcher: Launcher, path: Path | None = None) -> Path | None:
    """Write the stub where the project wants it, only when its content would change."""
    path = path or target()
    if path is None:
        return None
    text = render(launcher)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def refresh(launcher: Launcher) -> Path | None:
    """What ``Launcher()`` calls. A stub that cannot be written never stops a launcher."""
    if os.environ.get(ENVIRONMENT, "1") == "0":
        return None
    try:
        return write(launcher)
    except (OSError, LetifyError):
        return None


__all__ = [
    "DEFAULT_DIRECTORY",
    "ENVIRONMENT",
    "FILE_NAME",
    "class_name",
    "project_root",
    "refresh",
    "render",
    "target",
    "write",
]
