//! The extent of a module image handed to `cuModuleLoadData`.
//!
//! The entry point receives a pointer and no length, so the size has to come from the
//! image itself. This module owns that reading and nothing else: sending the image and
//! naming it by digest belong to the exports and the wire crate.

/// Bytes read from a module image whatever its format.
const WINDOW: usize = 4096;

/// The bytes of the module image that starts at `image`.
///
/// # Safety
///
/// `image` must point at a module image the caller owns, readable for its whole length.
pub unsafe fn module_image<'a>(image: *const u8) -> &'a [u8] {
    unsafe { std::slice::from_raw_parts(image, WINDOW) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use letify_wire::{Request, decode_request, encode_request};

    const FATBIN_MAGIC: u32 = 0xBA55_ED50;

    /// Send the image the way cuModuleLoadData does and return what the agent decodes.
    fn through_the_wire(image: &[u8]) -> Vec<u8> {
        let payload = unsafe { module_image(image.as_ptr()) }.to_vec();
        let request = Request::LoadModule { digest: letify_wire::digest(&payload), payload };
        match decode_request(&encode_request(&request)).unwrap() {
            Request::LoadModule { payload, .. } => payload,
            other => panic!("unexpected {other:?}"),
        }
    }

    /// A buffer longer than the image, so reading past the image would be visible.
    fn with_trailing_bytes(mut image: Vec<u8>) -> Vec<u8> {
        image.extend(std::iter::repeat_n(0xee, 2 * WINDOW));
        image
    }

    #[test]
    fn a_fatbinary_larger_than_4096_bytes_is_sent_whole() {
        let size = 10_000usize;
        let mut image = vec![0x11u8; size];
        image[0..4].copy_from_slice(&FATBIN_MAGIC.to_le_bytes());
        image[4..6].copy_from_slice(&1u16.to_le_bytes());
        image[6..8].copy_from_slice(&16u16.to_le_bytes());
        image[8..16].copy_from_slice(&(size as u64).to_le_bytes());
        let buffer = with_trailing_bytes(image.clone());
        assert_eq!(through_the_wire(&buffer), image);
    }

    #[test]
    fn an_elf_image_larger_than_4096_bytes_is_sent_whole() {
        let size = 9_000usize;
        let mut image = vec![0x22u8; size];
        image[0..4].copy_from_slice(b"\x7fELF");
        image[4] = 2; // ELFCLASS64
        image[5] = 1; // little endian
        image[0x20..0x28].copy_from_slice(&64u64.to_le_bytes()); // e_phoff
        image[0x36..0x38].copy_from_slice(&56u16.to_le_bytes()); // e_phentsize
        image[0x38..0x3a].copy_from_slice(&1u16.to_le_bytes()); // e_phnum
        let section_headers = 10u16;
        let shoff = size - 64 * section_headers as usize;
        image[0x28..0x30].copy_from_slice(&(shoff as u64).to_le_bytes()); // e_shoff
        image[0x3a..0x3c].copy_from_slice(&64u16.to_le_bytes()); // e_shentsize
        image[0x3c..0x3e].copy_from_slice(&section_headers.to_le_bytes()); // e_shnum
        let buffer = with_trailing_bytes(image.clone());
        assert_eq!(through_the_wire(&buffer), image);
    }

    #[test]
    fn a_ptx_image_larger_than_4096_bytes_is_sent_through_its_terminating_nul() {
        let mut image = b"// Generated by NVPTX\n".to_vec();
        image.extend(std::iter::repeat_n(b'a', 6_000));
        image.push(0);
        let buffer = with_trailing_bytes(image.clone());
        assert_eq!(through_the_wire(&buffer), image);
    }
}
